definitions:
  config:
    /hippo:configuration/hippo:frontend/cms/cms-admin/settings:
      jcr:primaryType: frontend:plugin
      hipposys:userrole: xm.system.admin
      plugin.class: org.bloomreach.forge.settings.management.SettingsPlugin
      /tabconfig:
        jcr:primaryType: frontend:pluginconfig
        /maintenance:
          jcr:primaryType: frontend:pluginconfig
          sequence: 1.0
          titleKey: maintenance
        /security:
          jcr:primaryType: frontend:pluginconfig
          sequence: 2.0
          titleKey: security
        /upload:
          jcr:primaryType: frontend:pluginconfig
          sequence: 3.0
          titleKey: upload
        /urlrewriter:
          jcr:primaryType: frontend:pluginconfig
          sequence: 4.0
          titleKey: urlrewriter
        /crispapi:
          jcr:primaryType: frontend:pluginconfig
          sequence: 5.0
          titleKey: crispapi
