definitions:
  config:
    /hippo:configuration/hippo:translations/hippo:cms/settingsmanagement:
      jcr:primaryType: hipposys:resourcebundles
      /en:
        jcr:primaryType: hipposys:resourcebundle
        maintenance: Maintenance
        security: Security
        upload: Upload
        urlrewriter: Url Rewriter
      /nl:
        jcr:primaryType: hipposys:resourcebundle
        maintenance: Onderhoud
        security: Beveiliging
        upload: Uploaden
        urlrewriter: Url Rewriter